import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#3636c5",
        "secondary": "#00658d",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001946",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#004c6b",
        "on-tertiary-fixed": "#07006c",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "on-primary-container": "#a5bdff",
        "surface-tint": "#2559bd",
        "electric-cyan": "#00AEEF",
        "background": "#f7f9fc",
        "on-surface-variant": "#434653",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b1c5ff",
        "surface-container-high": "#e6e8eb",
        "primary-container": "#0047ab",
        "inverse-primary": "#b1c5ff",
        "surface-container-low": "#f2f4f7",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e6",
        "outline-variant": "#c3c6d5",
        "on-primary-fixed-variant": "#00419e",
        "surface-white": "#FFFFFF",
        "outline": "#737784",
        "trust-blue": "#0047AB",
        "secondary-fixed-dim": "#82cfff",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#c6e7ff",
        "surface-dim": "#d8dadd",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001e2d",
        "on-secondary-container": "#004866",
        "inverse-on-surface": "#eff1f4",
        "tertiary-fixed": "#e1e0ff",
        "primary": "#00327d",
        "on-tertiary-container": "#b7b8ff",
        "surface-variant": "#e0e3e6",
        "surface-bright": "#f7f9fc",
        "on-primary": "#ffffff",
        "tertiary": "#1a12af",
        "surface-container": "#eceef1",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#2dbcfe",
        "slate-50": "#F8FAFC",
        "slate-100": "#F1F5F9",
        "slate-200": "#E2E8F0",
        "slate-300": "#CBD5E1",
        "slate-400": "#94A3B8",
        "slate-500": "#64748B",
        "slate-600": "#475569",
        "slate-700": "#334155",
        "slate-800": "#1E293B",
        "slate-900": "#0F172A",
        "slate-950": "#020617"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "section-padding": "80px",
        "stack-lg": "32px",
        "gutter": "24px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "stack-md": "16px",
        "base": "4px"
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
      fontFamily: {
        "display": ["Outfit", "sans-serif"],
        "title-lg": ["Outfit", "sans-serif"],
        "plus-jakarta-sans": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
};
export default config;
